== Create Operator Project

. Create a directory for the go operator and `cd` into it
+
----
mkdir $REPO_HOME/memcached-operator
cd $REPO_HOME/memcached-operator
----
+
. Use the operator SDK to create operator scaffolding: 
+
----
operator-sdk init --domain example.com \
    --repo github.com/example/memcached-operator \#<.>
----
<.> This refers to the go repo and is required when creating a project outside of $GOPATH/src, as scaffolded files require a valid module path
+
. Next use the `operator-sdk` to create a CRD that will represent the resource our operator will operate upon
+
----
operator-sdk create api --group cache --version v1alpha1 --kind Memcached --resource --controller #<.>
----
<.> This creates a CRD with with group `cache` version `v1alpha1` and Kind `Memcached`
+
. Now we need to edit one of the generated files at it represents the go struct the represents our CRD.  Define the API for the Memcached Custom Resource(CR) by modifying the Go type definitions at `$REPO_HOME/memcached-operator/api/v1alpha1/memcached_types.go` to have the following spec and status:
+
----
// MemcachedSpec defines the desired state of Memcached
type MemcachedSpec struct {
	//+kubebuilder:validation:Minimum=0
	// Size is the size of the memcached deployment
	Size int32 `json:"size"` <.>
}

// MemcachedStatus defines the observed state of Memcached
type MemcachedStatus struct {
	// Nodes are the names of the memcached pods
	Nodes []string `json:"nodes"` <.>
}
----
<.> The CRD will have one field, `size` that represents the number of memcached replicas we want
<.> This defines a list of nodes that will appear in the status field of the CR
+
. In the same file (`$REPO_HOME/memcached-operator/api/v1alpha1/memcached_types.go`) add the `+kubebuilder:subresource:status` marker to add a status subresource to the CRD manifest so that the controller can update the CR status without changing the rest of the CR object:
+
----
// Memcached is the Schema for the memcacheds API
//+kubebuilder:subresource:status
type Memcached struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MemcachedSpec   `json:"spec,omitempty"`
	Status MemcachedStatus `json:"status,omitempty"`
}
----
+
. After modifying the `*_types.go` file always run the following command to update the generated code for that resource type:
+
----
make generate #<.>
----
<.> The above makefile target will invoke the controller-gen utility to update the `api/v1alpha1/zz_generated.deepcopy.go` file to ensure our API’s Go type definitions implement the runtime.Object interface that all Kind types must implement.
+
. Next we need to generate kubernetes manifests from the structs:
+
----
make manifests #<.>
----
<.> This makefile target will invoke controller-gen to generate the CRD manifests at `$REPO_HOME/memcached-operator/config/crd/bases/cache.example.com_memcacheds.yaml`
+
. 
